### ISSUE TITLE
Injection no longer works with version 1.5.1 of the Azure function tools.

### ISSUE THREAD

**Issue by darrenhull** [daulet/Indigo.Functions#2]
This extension no longer works due to the recent changes to the functions Extension changes. it should be upgraded in line with this: https://github.com/Azure/azure-webjobs-sdk/issues/1865

**Comment by daulet** [comment]
Thanks for reporting! I've started to look into this, at first glance this would require substantial changes to each extension. Can you let me know what's the most pressing extension that you'd like to be fixed?

**Comment by darrenhull** [comment]
Its the standard dependency injection extension. Thanks

**Comment by daulet** [comment]
Fixed and the extension is out of prerelease now:
https://www.nuget.org/packages/Indigo.Functions.Injection/1.0.0

Don't forget to adhere to the 2.0 way of registering extensions in Startup class, see updated example for details.
